/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/bits.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/bits
bin/bits
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/container_api.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/container_api
bin/container_api
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/s3.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/s3
bin/s3
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/s2.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/s2
bin/s2
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/tree.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/tree
bin/tree
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/pack.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/pack
bin/pack
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/gain.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/gain
bin/gain
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/block_api.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/block_api
bin/block_api
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/quotient.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/quotient
bin/quotient
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/roundtrip.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/roundtrip
bin/roundtrip
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/container.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/container
bin/container
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/fuzz_unhopf.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/fuzz_unhopf
bin/fuzz_unhopf
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/comptime
bin/comptime
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/comptime_stress.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/comptime_stress
bin/comptime_stress
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/rot.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/rot
bin/rot
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/exact.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/exact
bin/exact
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/rate.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/rate
bin/rate
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/quant.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/quant
bin/quant
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/susp.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/susp
bin/susp
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/oct.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/oct
bin/oct
/usr/bin/g++ -std=c++23 -O3 -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -march=native -ffreestanding -nostdlib -nostdlib++ -fno-stack-protector -fexceptions -frtti -fasynchronous-unwind-tables -D__micron_eh -Wl,--eh-frame-hdr -m64 -Wall -Wextra -Wpedantic -Wno-variadic-macros -Wno-inline -fext-numeric-literals -Wno-odr -Wno-lto-type-mismatch -fdiagnostics-color=always -fconcepts-diagnostics-depth=2 tests/quat.cpp include/micron/start/start.s include/micron/start/start.cpp include/micron/start/eh_runtime.cpp -Iinclude/micron/tests -Iinclude/micron -Iinclude/micron/src -I/usr/include -L./libs/ -o bin/quat
bin/quat
