//  Copyright (c) 2026- David Lucius Severus
//
//  Distributed under the MIT License.
//  See accompanying file LICENSE or copy at
//  https://opensource.org/license/mit

#pragma once

#include "../config.hpp"
#include "../error.hpp"
#include "../level.hpp"
#include "s3.hpp"

#include <micron/math.hpp>
#include <micron/math/simd/atrig.hpp>
#include <micron/types.hpp>

//  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
//  recursive construction of S^(2n-1) -> leaves (S^(n-1) x S^(n-1))_eta -> ... -> S^3
//
//  a node is one (dim, d_q) pair;
//  an internal node's leaf i splits into child codes at d/cos(eta_i) and d/sin(eta_i);
//  those child distances are data independent but leaf dependent;
//  WARNING: if left alone the set of distinct (dim, d') skeletons __multiplies per level__
//  (~t per split, up to ~1e8 tables at dim 64), the paper glosses over this entirely;
//  hsc therefore snaps every child distance up to a fixed geometric grid, which preserves the minimum-distance
//  guarantee (a child built for a larger d', scaled by cos eta, is still >= d) and collapses the
//  reachable set to at most one node per grid member per level
//
//  the grid is generated by repeated multiplication with the dyadic rational 16303/16384
//  (~ 1/1.00497 per step, 2048 steps spanning [7.8e-5, 2])

namespace hsc
{

inline constexpr u32 k_grid_size = 2048;

inline constexpr auto k_grid = []() {
  struct table {
    u32 dq[k_grid_size]{};
  } t;
  f64 d = 2.0;
  for ( u32 g = 0; g < k_grid_size; ++g ) {
    t.dq[g] = dq_of(d);
    d = d * 16303.0 / 16384.0;
  }
  return t;
}();

//  smallest grid member >= d' (as d_q)
constexpr u32
grid_snap(f64 dp) noexcept
{
  if ( !(dp > 0.0) || dp >= 2.0 ) return k_grid.dq[0];
  const u32 dqp = static_cast<u32>(micron::math::mkbits::round_ns::ceil<f64>(dp * static_cast<f64>(dq_one)));
  if ( dqp >= k_grid.dq[0] ) return k_grid.dq[0];
  if ( dqp <= k_grid.dq[k_grid_size - 1] ) return k_grid.dq[k_grid_size - 1];
  u32 lo = 0, hi = k_grid_size - 1;      //  dq[] strictly decreasing: find the last entry >= dqp
  while ( lo < hi ) {
    const u32 mid = (lo + hi + 1) >> 1;
    if ( k_grid.dq[mid] >= dqp )
      lo = mid;
    else
      hi = mid - 1;
  }
  return k_grid.dq[lo];
}

struct tree_row {
  f64 ce = 0;      //  cos(eta_i)
  f64 se = 0;      //  sin(eta_i)
  u32 c1 = 0;      //  child node id at d/ce (snapped)
  u32 c2 = 0;      //  child node id at d/se (snapped)
};

struct tree_node {
  u32 dim_log2 = 2;
  u32 dq = 0;
  u32 count = 0;      //  leaves (internal) / s3 leaf entries (dim 4)
  u32 half = 0;
  f64 deta = 0;
  u64 m_mod = 0;      //  cardinality % 2^64 (exact for dim 4)
  u32 rows_at = 0;
  u32 s3_at = 0;      //  dim 4: slice into the s3 leaf arena
};

struct tree_arena {
  tree_node *nodes = nullptr;
  u32 node_cap = 0, node_count = 0;
  tree_row *rows = nullptr;
  u32 row_cap = 0, row_count = 0;
  s3_leaf *leaves = nullptr;
  u32 leaf_cap = 0, leaf_count = 0;
};

struct tree_skeleton {
  const tree_node *nodes = nullptr;
  const tree_row *rows = nullptr;
  const s3_leaf *leaves = nullptr;
  u32 root = 0;
  u32 dim_log2 = 2;
  u32 dq = 0;
};

//  s3 view of a dim-4 node
constexpr s3_skeleton
__s3_of(const tree_skeleton &sk, const tree_node &nd) noexcept
{
  return s3_skeleton{ sk.leaves + nd.s3_at, nd.count, nd.half, __s3_d(nd.dq), nd.deta, nd.m_mod };
}

constexpr max_t
tree_build(u32 dim_log2, u32 dq, tree_arena &ar) noexcept
{
  for ( u32 i = 0; i < ar.node_count; ++i )
    if ( ar.nodes[i].dim_log2 == dim_log2 && ar.nodes[i].dq == dq ) return static_cast<max_t>(i);

  if ( ar.node_count >= ar.node_cap ) [[unlikely]]
    return fail(error::oom);
  const u32 id = ar.node_count++;

  if ( dim_log2 == 2 ) {
    const u32 need = s3_leaf_count(dq);
    if ( ar.leaf_count + need > ar.leaf_cap ) [[unlikely]]
      return fail(error::oom);
    const u32 at = ar.leaf_count;
    ar.leaf_count += need;
    const s3_skeleton s3 = s3_build(dq, ar.leaves + at);
    ar.nodes[id] = tree_node{ 2, dq, s3.count, s3.half, s3.deta, s3.m_total, 0, at };
    return static_cast<max_t>(id);
  }

  const f64 d = __s3_d(dq);
  const f64 deta = 2.0 * micron::asin(d * 0.5);
  const u32 half = __s3_half(d);
  const u32 count = 2 * half + 1;
  if ( ar.row_count + count > ar.row_cap ) [[unlikely]]
    return fail(error::oom);
  const u32 at = ar.row_count;
  ar.row_count += count;
  ar.nodes[id] = tree_node{ dim_log2, dq, count, half, deta, 0, at, 0 };

  u64 m_mod = 0;
  for ( u32 x = 0; x < count; ++x ) {
    const i64 i = static_cast<i64>(x) - static_cast<i64>(half);
    const f64 eta = k_pi_4 + static_cast<f64>(i) * deta;
    f64 se = 0, ce = 0;
    micron::sincos(eta, se, ce);
    const u32 dq1 = grid_snap(ce > 0.0 ? d / ce : 2.0);
    const u32 dq2 = grid_snap(se > 0.0 ? d / se : 2.0);
    const max_t r1 = tree_build(dim_log2 - 1, dq1, ar);
    if ( r1 < 0 ) [[unlikely]]
      return r1;
    const max_t r2 = tree_build(dim_log2 - 1, dq2, ar);
    if ( r2 < 0 ) [[unlikely]]
      return r2;
    ar.rows[at + x] = tree_row{ ce, se, static_cast<u32>(r1), static_cast<u32>(r2) };
    m_mod += ar.nodes[static_cast<u32>(r1)].m_mod * ar.nodes[static_cast<u32>(r2)].m_mod;
  }
  ar.nodes[id].m_mod = m_mod;
  return static_cast<max_t>(id);
}

constexpr tree_skeleton
tree_view(const tree_arena &ar, u32 root, u32 dim_log2, u32 dq) noexcept
{
  return tree_skeleton{ ar.nodes, ar.rows, ar.leaves, root, dim_log2, dq };
}

constexpr u64
tree_m_mod64(const tree_skeleton &sk) noexcept
{
  return sk.nodes[sk.root].m_mod;
}

inline constexpr u32 k_max_inodes = 31;      //  TOTAL nodes at dim 64 (15 internal + 16 base); leaf[]
                                             //  only needs the 15 internal slots, kept oversized
inline constexpr u32 k_max_bnodes = 16;      //  4D base nodes at dim 64

struct tree_fields {
  u32 leaf[k_max_inodes]{};
  u64 base[k_max_bnodes]{};
};

constexpr u32
tree_inode_count(u32 dim_log2) noexcept
{
  return (1u << (dim_log2 - 2)) - 1;      //  n/4 - 1
}

constexpr u32
tree_bnode_count(u32 dim_log2) noexcept
{
  return 1u << (dim_log2 - 2);      //  n/4
}

constexpr void
__tree_quantize(const tree_skeleton &sk, u32 id, const f64 *y, tree_fields &out, u32 &pi, u32 &pb, u32 refine) noexcept
{
  const tree_node &nd = sk.nodes[id];
  if ( nd.dim_log2 == 2 ) {
    const s3_skeleton s3 = __s3_of(sk, nd);
    out.base[pb++] = s3_quantize(s3, y, refine);
    return;
  }
  const u32 h = 1u << (nd.dim_log2 - 1);      //  half dimension
  f64 sa = 0, sb = 0;
  for ( u32 c = 0; c < h; ++c ) sa += y[c] * y[c];
  for ( u32 c = h; c < 2 * h; ++c ) sb += y[c] * y[c];
  const f64 eta = micron::math::mk::atan2_pos(__sqrt(sb), __sqrt(sa));
  const i64 half = static_cast<i64>(nd.half);
  i64 i = static_cast<i64>(__round((eta - k_pi_4) / nd.deta));
  i = i < -half ? -half : i;      //  two selects, not a nested branch pair (see s3_quantize)
  i = i > half ? half : i;
  const u32 x = static_cast<u32>(i + half);
  out.leaf[pi++] = x;
  const tree_row &rw = sk.rows[nd.rows_at + x];
  __tree_quantize(sk, rw.c1, y, out, pi, pb, refine);
  __tree_quantize(sk, rw.c2, y + h, out, pi, pb, refine);
}

constexpr void
tree_quantize(const tree_skeleton &sk, const f64 *y, tree_fields &out, u32 refine = 0) noexcept
{
  u32 pi = 0, pb = 0;
  __tree_quantize(sk, sk.root, y, out, pi, pb, refine);
}

constexpr void
__tree_decode(const tree_skeleton &sk, u32 id, const tree_fields &in, u32 &pi, u32 &pb, f64 *out) noexcept
{
  const tree_node &nd = sk.nodes[id];
  if ( nd.dim_log2 == 2 ) {
    const s3_skeleton s3 = __s3_of(sk, nd);
    s3_decode(s3, in.base[pb++], out);
    return;
  }
  const u32 h = 1u << (nd.dim_log2 - 1);
  const u32 x = in.leaf[pi++];
  const tree_row &rw = sk.rows[nd.rows_at + x];
  __tree_decode(sk, rw.c1, in, pi, pb, out);
  __tree_decode(sk, rw.c2, in, pi, pb, out + h);
  for ( u32 c = 0; c < h; ++c ) out[c] *= rw.ce;
  for ( u32 c = 0; c < h; ++c ) out[h + c] *= rw.se;
}

constexpr void
tree_decode(const tree_skeleton &sk, const tree_fields &in, f64 *out) noexcept
{
  u32 pi = 0, pb = 0;
  __tree_decode(sk, sk.root, in, pi, pb, out);
}

};      //  namespace hsc
