#!/usr/bin/env python3
"""Assemble BENCHMARKS.md: hsc against lossless coders, plus the model and vector results.

Runs zstd/xz/gzip/bzip2 over the SAME 512 KiB prefix of each corpus file that
benches/compression_ratio_bench.cpp measures, so the two columns are comparable, then stitches the
bench, model, preset-chart and vector-eval outputs into one document.

The headline section is scripts/preset_chart.py: the stock quant.hpp preset ladder and the coders
it would actually replace, in ONE table, on f32 model tensors and on the byte corpus.

    python3 scripts/ratio_report.py > BENCHMARKS.md
    python3 scripts/ratio_report.py --baselines-only
"""

import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import compression_ratio_model as crm      # noqa: E402  (needs the path insert above)
import preset_chart                        # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORPUS = os.path.join(ROOT, "corpus")
WORK = 1 << 19  # must match k_work in benches/compression_ratio_bench.cpp

FILES = [
    ("urandom", "urandom.bin", "/dev/urandom"),
    ("random", "random.bin", "/dev/random (same CSPRNG)"),
    ("image-raw", "photo.ppm", "raw RGB pixels"),
    ("image-png", "photo.png", "PNG bytes (already coded)"),
    ("json", "data.json", "JSON"),
    ("text", "text.txt", "natural-language prose"),
    ("source", "micron_src.txt", "C++ source (micron.cpp)"),
    ("records", "records.bin", "fixed-schema binary records"),
    ("mixed", "mixed.bin", "unstructured, interleaved"),
    ("runs", "runs.bin", "synthetic long runs"),
    ("words", "words.bin", "synthetic Zipf words"),
]

CODERS = [
    ("zstd-19", ["zstd", "-19", "-q", "-c"]),
    ("xz-9", ["xz", "-9", "-c"]),
    ("bzip2-9", ["bzip2", "-9", "-c"]),
    ("gzip-9", ["gzip", "-9", "-c"]),
]


def baselines():
    rows = []
    for label, fn, note in FILES:
        p = os.path.join(CORPUS, fn)
        if not os.path.exists(p):
            continue
        with open(p, "rb") as f:
            data = f.read(WORK)
        rec = {"label": label, "note": note, "n": len(data)}
        for cname, cmd in CODERS:
            if shutil.which(cmd[0]) is None:
                rec[cname] = None
                continue
            r = subprocess.run(cmd, input=data, capture_output=True)
            rec[cname] = len(r.stdout) if r.returncode == 0 and r.stdout else None
        rows.append(rec)
    return rows


def md_baselines(rows):
    out = []
    hdr = "| corpus | what it is | n (B) | " + " | ".join(c for c, _ in CODERS) + " |"
    out.append(hdr)
    out.append("|---|---|---:|" + "---:|" * len(CODERS))
    for r in rows:
        cells = []
        for cname, _ in CODERS:
            v = r[cname]
            cells.append("n/a" if v is None else f"{r['n'] / v:.2f}x")
        out.append(f"| `{r['label']}` | {r['note']} | {r['n']:,} | " + " | ".join(cells) + " |")
    return "\n".join(out)


def run(cmd, cwd=ROOT):
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    return r.stdout if r.returncode == 0 else (r.stdout + "\n" + r.stderr)


def section(text, marker_start, marker_end=None):
    """pull one section out of a bench's output"""
    if marker_start not in text:
        return "(not present in output)"
    s = text.index(marker_start)
    e = text.index(marker_end, s) if marker_end and marker_end in text[s:] else len(text)
    return text[s:e].rstrip()


def main():
    if "--baselines-only" in sys.argv:
        print(md_baselines(baselines()))
        return 0

    bench = os.path.join(ROOT, "bin", "compression_ratio_bench")
    vbench = os.path.join(ROOT, "bin", "vector_bench")
    have_bench = os.path.exists(bench)

    text = run([bench]) if have_bench else ""
    saved = None
    if text:
        fd, saved = tempfile.mkstemp(prefix="hsc_bench_", suffix=".txt")
        with os.fdopen(fd, "w") as f:
            f.write(text)

    print("# hsc benchmarks — compression ratio, distortion, and open-weight vectors")
    print()
    print("Generated by `python3 scripts/ratio_report.py > BENCHMARKS.md`. The corpus is not in the")
    print("repo; build it with `python3 scripts/corpus.py fetch && python3 scripts/corpus.py models`.")
    print()
    print("## How to read every table here")
    print()
    print("hsc is **fixed-rate**. For a given `(mode, dim, level, gain_bits)` the compressed size is")
    print("identical for `/dev/urandom` and for JSON — that is the library's guarantee, and it means")
    print("**the ratio column carries no information about the data**. What a corpus decides is the")
    print("*distortion* at that rate. So:")
    print()
    print("* the fixed-rate grid varies `rmse`/`psnr` down a corpus and holds `ratio` constant;")
    print("* the **quality-matched** table fixes a distortion target and searches for the cheapest")
    print("  configuration that meets it — that ratio *is* data-dependent, and it is the only number")
    print("  here that answers \"what does hsc get on my data?\";")
    print("* a `dg=1` row is **degenerate**: `shape_bits == 0`, the recursion collapsed to `M == 1`,")
    print("  the shape field has zero width and the record carries the gain alone. Those rows show")
    print("  enormous ratios and are not compression. They are excluded from every search.")
    print()
    print("Two rate conventions appear below and they are not the same number. hsc rows in the")
    print("preset chart and the fixed-rate grid print the **payload** rate — block records only —")
    print("which is what the `quant.hpp` preset constants state and what `tests/quant.cpp` pins")
    print("against `hsc::rate()`. The frame is a flat 48 bytes per stream (40 header + 8 trailer),")
    print("so `qplan::bits_per_weight`, which counts it along with the final pad bits, is always")
    print("slightly larger. The measured `ratio` column in the same rows is FRAMED — whole stream")
    print("over input, 48 B included — so `ratio` and `8 / bits-per-byte` differ by the frame share.")
    print("Coder rows count every byte the coder emits.")
    print()
    print("## Presets vs coders — the one chart")
    print()
    print("`src/hsc/quant.hpp` declares a seven-entry preset ladder — `q_min` … `q_finest` — and")
    print("those are the library's own default answers to \"how should I store this?\". This is the")
    print("only place in the report that measures them, and it puts them in the same table as the")
    print("alternatives: the four lossless coders, and the int-N a weight quantizer would ship.")
    print()
    print("Read the `lossy` column first. zstd/xz/bzip2/gzip reproduce the input exactly and their")
    print("ratio is whatever the data allows — unknowable until they have run. int-N and hsc are")
    print("lossy; hsc's ratio is a constant of the configuration, guaranteed on any input at all.")
    print("The two blocks use different PSNR references (peak-magnitude for f32 tensors, 8-bit full")
    print("scale for bytes) and must not be read as one table.")
    print()
    print("```")
    print(preset_chart.report(saved))
    print("```")
    print()
    print("## hsc vs lossless coders, same 512 KiB prefix")
    print()
    print("**This is context, not a contest.** These coders are lossless; hsc is lossy. The point of")
    print("the table is the shape of the two columns, not a winner: an entropy coder's ratio swings")
    print("from 1.00x (incompressible) to hundreds (long runs) and it cannot promise anything in")
    print("advance, while hsc's is a constant it guarantees on any input at all.")
    print()
    print(md_baselines(baselines()))
    print()
    cells = [(3, 6), (4, 6), (6, 6), (6, 2)]      # (dim_log2, level), computed, never typed in
    q = [f"{crm.rate(dim_log2=dl, level=lv)['ratio']:.2f}x at dim{1 << dl} L{lv}" for dl, lv in cells]
    print("For contrast, hsc's **payload-rate** ratio is set by the configuration alone and is the")
    print(f"same for every one of those inputs: {q[0]}, {q[1]}, {q[2]},")
    print(f"{q[3]} — with the distortion cost measured below. (The measured grid rows")
    print("print the framed ratio, a hair lower: the 48-byte frame over a 512 KiB prefix.)")
    print()

    if have_bench:
        print("## Rate reference — data-independent by construction")
        print()
        print("```")
        print(section(text, "-- rate reference"))
        print("```")
        print()
        print("## Quality-matched: the cheapest configuration meeting a distortion target")
        print()
        print("The data-dependent ratio. PSNR is over 8-bit full scale (`20*log10(255/rmse)`).")
        print()
        print("```")
        print(section(text, "-- quality-matched", "-- rate reference"))
        print("```")
        print()
        print("## Fixed-rate grid, per corpus")
        print()
        print("```")
        print(section(text, "-- fixed-rate grid --", "-- quality-matched"))
        print("```")
        print()
    else:
        print("_(bin/compression_ratio_bench not built — run `duck batch build.duck`)_\n")

    print("## The compression-ratio model")
    print()
    print("Rate is **exact** — a closed form validated cell by cell against real streams. Distortion")
    print("is **empirical**, `rmse ~= min(kappa(dim) * d * sigma, sqrt(2) * sigma)`, with `sigma` the")
    print("RMS of the centered bytes. The fitted `kappa(dim)` tracks `0.29*sqrt(dim)`, and the")
    print("residuals are reported split by validity domain rather than averaged into one flattering")
    print("number.")
    print()
    print("```")
    print(run([sys.executable, os.path.join(ROOT, "scripts", "compression_ratio_model.py")]).rstrip())
    print("```")
    print()

    if os.path.exists(vbench) and os.path.exists(os.path.join(CORPUS, "models", "manifest.json")):
        print("## Open-weight model vectors")
        print()
        print("Real tensors from `sentence-transformers/all-MiniLM-L6-v2` and")
        print("`HuggingFaceTB/SmolLM2-135M`, scored against the int-N a weight quantizer would charge")
        print("for the same storage. Compare a row against the int-N with the **same bits/weight**.")
        print()
        print("```")
        print(run([sys.executable, os.path.join(ROOT, "scripts", "vector_eval.py")]).rstrip())
        print("```")
    else:
        print("_(vector results need `duck batch build.duck` and `scripts/corpus.py models`)_")
    if saved:
        os.unlink(saved)
    return 0


if __name__ == "__main__":
    sys.exit(main())
